# Generated by Django 5.0.3 on 2024-04-01 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefonos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registro.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
